version: 0.0
os: linux
files:
  - source: ./sharpsell-backend
    destination: /var/www/html/sharpsell-backend
  - source: ./core-service-api
    destination: /home/ec2-user/core-service-api
hooks:
  BeforeInstall:
    - location: bin/auto-deploy
    - location: deploy/auto-deploy
      timeout: 3600
      runas: root  
  ApplicationStop:
    # - location: scripts/stop_server
      # timeout: 3600
      # runas: root
  ApplicationStart:
    # - location: scripts/start_server
      # timeout: 3600
      # runas: root
